---
title: "ARI EEG analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{eeg_lst}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(ARIeeg)
library(dplyr)
library(eeguana)
load(system.file("extdata", "data_eeg_emotion.RData", package = "ARIeeg"))
```

We apply ARI using EEG data

```{r}
data = utilsTOlst(data=dati)
```

Drop off final 5 channels: 

```{r}
chan_to_rm <- c("RM"  ,  "EOGvo" ,"EOGvu"
                , "EOGhl", "EOGhr")
data <- 
  data %>%
  select(-one_of(chan_to_rm))
```

Segments data and select two conditions:

```{r}
data_seg <- data %>%
  eeg_segment(.description %in% c(4,5),
              lim = c(min(dati$timings$time), max(dati$timings$time))
  ) %>% eeg_baseline()  %>%
  mutate(
    condition =
      description
  ) %>%
  select(-c(type,description))
```

# Simes family

$\delta = 0$

```{r}
out <-ARIpermEEG(data=data_seg, alpha=0.1, family="Simes", delta=0, ct=c(0,1), alternative = "two.sided", timeS = c(100:400), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

$\delta = 50$

```{r}
out1 <- ARIpermEEG(data=data_seg, alpha=0.1, family="Simes", delta=50, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

$\delta = 100$

```{r}
out2 <- ARIpermEEG(data=data_seg, alpha=0.1, family="Simes", delta=100, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

# Finner family

$\delta = 0$

```{r}
out3 <- ARIpermEEG(data=data_seg, alpha=0.1, family="Finner", delta=0, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

$\delta = 50$

```{r}
out4 <- ARIpermEEG(data=data_seg, alpha=0.1, family="Finner", delta=50, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

$\delta = 100$

```{r}
out5 <- ARIpermEEG(data=data_seg, alpha=0.1, family="Finner", delta=100, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

# Beta 

```{r}
out6 <- ARIpermEEG(data=data_seg, alpha=0.1, family="beta", delta=0, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

# higher criticism 

```{r}
out7 <- ARIpermEEG(data=data_seg, alpha=0.1, family="higher.criticism", delta=0, ct=c(0,1), alternative = "two.sided", timeS = c(100:500), dist = 53, formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
```

# parametric ARI

```{r}
out8<-ARIeeg(data =data_seg, alpha = 0.1,alternative ="two.sided", timeS = c(100:500),dist = 53,formula = signal ~ condition + Error(.subj/(condition)), variable = c(".subj", "condition"), B = 5000, eff = "condition")
  
```




